# Generated by Django 5.2.11 on 2026-02-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_location',
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(choices=[('Ground', 'Ground'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='Ground', max_length=20),
            preserve_default=False,
        ),
    ]
