# Generated by Django 5.2.11 on 2026-03-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Lab', 'Lab'), ('Classroom', 'Classroom'), ('Seminar Hall', 'Seminar Hall'), ('Conference Hall', 'Conference Hall')], max_length=100),
        ),
    ]
