# Generated by Django 5.2.11 on 2026-03-07 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_roomtype_alter_room_options_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
            preserve_default=False,
        ),
    ]
