# Generated by Django 5.2.11 on 2026-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_room_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
